[package]
name = "server"
version = "0.1.0"
authors = ["Isaac Woods"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
tokio = "1"
commonplace = { path = "../commonplace" }
serde = "1"
bincode = "1"
sled = "0.34"
tantivy = "0.15"
